# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:

services:
    tecspro_comun.comun_mailer:
        class: Tecspro\Bundle\ComunBundle\Services\Mailer
        arguments: ["@mailer"]